/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/hacker-room.glb -o src/components/HackerRoom.jsx 
*/

import React from 'react'
import { useGLTF, useTexture } from '@react-three/drei'

export function HackerRoom(props) {
  const { nodes, materials } = useGLTF('/models/hacker-room.glb')
  
  // Inject the custom developer workstation screen textures
  const monitorTexture = useTexture('/textures/desk/monitor.png')
  const screenTexture = useTexture('/textures/desk/screen.png')

  return (
    <group {...props} dispose={null}>
      {/* Dynamic Screen containing the IDE/architecture code */}
      <mesh geometry={nodes.screen_screens_0.geometry}>
        <meshBasicMaterial map={screenTexture} />
      </mesh>
      
      {/* Screen glass reflectives */}
      <mesh geometry={nodes.screen_glass_glass_0.geometry} material={materials.glass} />
      
      {/* Rest of the Hacker Room desk props with default material configurations */}
      <mesh geometry={nodes.table_table_mat_0_1.geometry} material={materials.table_mat} />
      <mesh geometry={nodes.table_table_mat_0_2.geometry} material={materials.computer_mat} />
      <mesh geometry={nodes.table_table_mat_0_3.geometry} material={materials.server_mat} />
      <mesh geometry={nodes.table_table_mat_0_4.geometry} material={materials.vhsPlayer_mat} />
      <mesh geometry={nodes.table_table_mat_0_5.geometry} material={materials.stand_mat} />
      <mesh geometry={nodes.table_table_mat_0_6.geometry} material={materials.mat_mat} />
      <mesh geometry={nodes.table_table_mat_0_7.geometry} material={materials.arm_mat} />
      <mesh geometry={nodes.table_table_mat_0_8.geometry} material={materials.tv_mat} />
      <mesh geometry={nodes.table_table_mat_0_9.geometry} material={materials.cables_mat} />
      <mesh geometry={nodes.table_table_mat_0_10.geometry} material={materials.props_mat} />
      <mesh geometry={nodes.table_table_mat_0_11.geometry} material={materials.ground_mat} />
      <mesh geometry={nodes.table_table_mat_0_12.geometry} material={materials.key_mat} />
    </group>
  )
}

useGLTF.preload('/models/hacker-room.glb')
